#!/bin/bash
cd ~
/usr/sbin/project-builder-suse-umount
sudo rm -rf proot
sudo mkdir proot
cd proot
sudo tar xjf /usr/share/pdk/platforms/mccaslin/build-rootstrap.tar.bz2 ./
sudo cp /usr/sbin/project-builder ./usr/sbin
sudo mkdir ./usr/share/pdk
sudo cp -R ./var/lib/apt /var/lib
sudo cp -R ./var/lib/dpkg /var/lib
sudo cp -R ./var/cache /var
sudo cp ~/.Xauthority ./home
/usr/sbin/project-builder-suse-mount
sudo chroot . <<EOF
export PATH=/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:$PATH
apt-get --assume-yes --force-yes install language-pack-en xauth bzip2 python-gnome2 python-glade2
mkdir $HOME
cp /home/.Xauthority $HOME
EOF
